FROM node:16-alpine as builder

RUN apk add --no-cache yarn

# install types package
WORKDIR /app
COPY types/ ./types/
WORKDIR /app/types
RUN yarn install

# install client dependencies
WORKDIR /app/client
COPY client/package.json ./
COPY client/yarn.lock ./
RUN yarn install

COPY client/ ./

# build client
RUN yarn build


FROM nginx

COPY --from=builder /app/client/build /usr/share/nginx/html
